### ISSUE TITLE
Neue Features: Registrieren für led_events, Visualisierer für das EAModul.

### ISSUE THREAD

**Issue by pintman** [pintman/ea_rpi_modul#10]
Nur zur Information:

Es gibt zwei neue Features in eapi ab Version 0.4.1.
1. Man kann sich jetzt auch für Änderungen an den LEDs registrieren: 

`pydoc3 eapi.hw.EAModul.led_event_registrieren`
oder
http://pythonhosted.org/eapi/classeapi_1_1hw_1_1EAModul.html#a2099c375f1b27aaffc626d9eea1df5a2
2. Es gibt eine Visualisierung für die LEDs in einer GUI und auf der Konsole: 

`pydoc3 eapi.gui`
oder
http://pythonhosted.org/eapi/namespaceeapi_1_1gui.html

**Comment by pintman** [comment]
Es gibt auch zwei Demoprogramme für die Visualsierung, die sich wie folgt starten lassen:

```
python3 -m eapi.gui
```

**Comment by elektroschule** [comment]
Getestet und für gut befunden. :)

Kleine Anmerkung: Die Demo "demo_cli" kann nicht sinnvoll verwendet werden, da sie sofort beendet wird, bevor man die Taster betätigen kann.

**Comment by pintman** [comment]
Hast du eine Fehlermeldung bekommen?
Hast du unter Windows oder Linux getestet?

**Comment by pintman** [comment]
Fehler liegt an einer fehlenden Warteschleife am Ende. Werde ich fixen.

**Comment by pintman** [comment]
In Version 0.4.2 sollte es gefixt sein. Kannst du einmal testen?

**Comment by elektroschule** [comment]
> Hast du eine Fehlermeldung bekommen?
> Hast du unter Windows oder Linux getestet?

Keine Fehlermeldung. Linux, wie immer. Auf dem RasPi läuft ja sowieso Raspbian.

> Fehler liegt an einer fehlenden Warteschleife am Ende. Werde ich fixen.

Sowas hatte ich erwartet.

> In Version 0.4.2 sollte es gefixt sein. Kannst du einmal testen?

Jetzt funktioniert es. :)

**Comment by pintman** [comment]
Super. :) Dann schließe ich an dieser Stelle.
